= Neo4j Spring Boot Starter
:sectanchors:
// tag::properties[]
:groupId: org.neo4j.driver
:artifactId: neo4j-java-driver-spring-boot-starter
:neo4j-java-driver-spring-boot-starter_version: 4.0.1.0
:spring-boot_version: 2.2.5.RELEASE
:neo4j_version: 4.0.1
:config_prefix: org.neo4j.driver
:gh_base: https://github.com/neo4j/neo4j-java-driver-spring-boot-starter

// end::properties[]

image:https://img.shields.io/maven-central/v/org.neo4j.driver/neo4j-java-driver-spring-boot-starter.svg[Maven Central,link=http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.neo4j.driver%22%20AND%20a%3A%22neo4j-java-driver-spring-boot-starter%22]

[abstract]
--
A Spring Boot starter with automatic configuration for the https://github.com/neo4j/neo4j-java-driver[Neo4j Java Driver].
--

== Introduction

This starter provides a convenient way to configure all aspects of the Neo4j-Java-Driver from within a Spring Boot application.
It provides a single, managed Spring Bean of type `org.neo4j.driver.Driver`, configured to your needs.

The starter does not add any additional functionality on top of the driver, but only exposes the drivers configuration in a Spring friendly way.
However, it configures the driver to use Springs JCL logging variation by default.

The 4.0.x. line of the starter only supports the 4.0.x line of the Neo4j Java Driver.
It is tested and developed against https://spring.io/projects/spring-boot[Spring Boot {spring-boot_version}].

The starter supports Neo4j server mode only, that is: A connection against a Neo4j server over the Bolt protocol.

== Manual

For a gentle introduction and some getting started guides, please use our
link:https://neo4j.github.io/neo4j-java-driver-spring-boot-starter/[Manual].
The manual contains descriptions of all examples, which you'll find in the project source directory under https://github.com/neo4j/neo4j-java-driver-spring-boot-starter/tree/master/examples[examples].
