= Testing against the Neo4j harness

We provide a special module that brings in the community edition of the Neo4j harness
and some additional utilities that hopefully make your life easier.

[source,xml,subs="verbatim,attributes"]
.pom.xml
----
<dependency>
    <groupId>org.neo4j.driver</groupId>
    <artifactId>neo4j-java-driver-test-harness-spring-boot-autoconfigure</artifactId>
    <version>{neo4j-java-driver-spring-boot-starter_version}</version>
    <scope>test</scope>
</dependency>
----

If you need the enterprise edition, bring in the module like this:

[source,xml,subs="verbatim,attributes"]
.pom.xml
----
<dependency>
    <groupId>org.neo4j.driver</groupId>
    <artifactId>neo4j-java-driver-test-harness-spring-boot-autoconfigure</artifactId>
    <version>{neo4j-java-driver-spring-boot-starter_version}</version>
    <scope>test</scope>
    <exclusions>
        <exclusion>
            <groupId>org.neo4j.test</groupId>
            <artifactId>neo4j-harness</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>com.neo4j.test</groupId>
    <artifactId>neo4j-harness-enterprise</artifactId>
    <!-- See below regarding Neo4j version -->
    <version>3.5.15</version>
    <scope>test</scope>
    <exclusions>
        <exclusion>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-nop</artifactId>
        </exclusion>
    </exclusions>
</dependency>
----

The disadvantage: It brings a ton of dependencies.
The advantage: It starts very fast.
If you don't want to have the dependencies and can live with a slower start, we recommend https://www.testcontainers.org/modules/databases/neo4j/[Testcontainers].

They are easy to use and can be configured as shown in <<option1,option 1 below>> as well.

== Neo4j 3.5 or Neo4j 4.0?

Neo4j 3.5 and 4.0 have different requirements.
Neo4j 4.0 requires at least JDK 11.
We understand that not all of you are ready to go beyond JDK 8 (but you should).
Therefore we decided to build the Test harness support by default against Neo4j 3.5 and JDK 8.

To use Neo4j 4.0 as in the following examples, please add this to your build file

[source,xml,subs="verbatim,attributes"]
.pom.xml
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.neo4j.test</groupId>
            <artifactId>neo4j-harness</artifactId>
            <version>{neo4j_version}</version>
        </dependency>
    </dependencies>
</dependencyManagement>
----

Be aware that the type of the 4.0 test harness is `org.neo4j.harness.Neo4j`.
The following examples use 4.0 (`org.neo4j.harness.Neo4j`) but are applicable to `ServerControlls`, too.

== Starting up the Neo4j harness and making Spring aware of it

There many different options.
The main question is always: *How to make Spring Boot aware that it should use different configuration properties?*

[[option1]]
=== Option 1: Add the embedded server as a Spring bean (recommended approach)

The recommended approach is shown in `MoviesServiceAlt1Test`:

[source,java,tabsize=4]
[[test-harness-example-option1]]
.MoviesServiceAlt1Test.java
----
include::src/test/java/org/neo4j/doc/driver/springframework/boot/simple/MoviesServiceAlt1Test.java[tags=test-harness-example-option1]
----
<.> This is a test configuration only applicable for this test
<.> This turns the embedded instance into a Spring Bean, bound to Springs lifecycle

The autoconfiguration module for the test harness makes the starter aware of the harness and reconfigures the driver to use it.
This would be the recommended way of doing things.

[[option2]]
=== Option 2: Use the provided harness instance

`MoviesServiceAlt2Test.java` demonstrates the fully automatic configuration of test harness and driver:

[source,java,tabsize=4]
[[test-harness-example-option2]]
.MoviesServiceAlt2Test.java
----
include::src/test/java/org/neo4j/doc/driver/springframework/boot/simple/MoviesServiceAlt2Test.java[tags=test-harness-example-option2]
----
<.> As you don't have access to the builder, you have to provide your fixtures through the embedded database service.

This may come in handy in some scenarios, but generally, using the builder API as shown above is preferable.
On the plus side: The automatic configuration of the harness takes care of disabling the embedded webserver (for Neo4j 4.0+).

[[option3]]
=== Option 3: Start Neo4j outside Spring and apply its URL to configuration

Here we start the embedded instance from the JUnit 5 context and
than use an `org.springframework.context.ApplicationContextInitializer` to apply `TestPropertyValues` to the Spring environment.

NOTE: You don't actually need `neo4j-java-driver-test-harness-spring-boot-autoconfigure` for this solution. It's enough to have the
      Test harness - either 3.5.x or 4.0.x or Community or enterprise edition on the classpath.
      If you have the test harness autoconfiguration support on the classpath, you have to explicitly disable it.

[source,java,tabsize=4]
[[test-harness-example-option3]]
.MoviesServiceAlt3Test.java
----
include::src/test/java/org/neo4j/doc/driver/springframework/boot/simple/MoviesServiceAlt3Test.java[tags=test-harness-example-option3]
----
<.> Disable the autoconfiguration (only needed if you have `neo4j-java-driver-test-harness-spring-boot-autoconfigure` on the classpath)
<.> Use a JUnit `BeforeAll` to boot Neo4j
<.> The driver uses only the Bolt port, not the http port, so we don't need the embedded webserver (that option is only available in Neo4j Harness 4.0+)
<.> Close it in an `AfterAll`
<.> This the essential part: Apply the new configuration values.
    This uses an `ApplicationContextInitializer` which can inject `TestPropertyValues` into the context before the context starts.

This is a good solution It works well with both Community and enterprise edition and decouples the creation of the server from configuring the client.
The downside of it: You have to configure a lot of stuff manually and your mileage may vary.

Since Spring Boot 2.2.6 you have an additional option:
As of Spring Framework 5.2.5, the TestContext framework provides support for dynamic property sources via the `@DynamicPropertySource` annotation.
This annotation can be used in integration tests that need to add properties with dynamic values.
For more information, have a look at the https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/testing.html#testcontext-ctx-management-dynamic-property-sources[Spring Framework reference].

<<test-harness-example-option4>> is conceptionally the same variant as <<test-harness-example-option3>> but much more concise:

[source,java,tabsize=4]
[[test-harness-example-option4]]
.MoviesServiceAlt4Test.java
----
include::src/test/java/org/neo4j/doc/driver/springframework/boot/simple/MoviesServiceAlt4Test.java[tags=test-harness-example-option4]
----



=== Running your own driver bean

You can always fall back to create your own driver bean, but that actually disables the starter for the driver.
That is of course ok, but you might end up with a very different configuration in test than in production.
For example the driver will not use Spring logging, but its own default.
