[[manual-introduction]]
= Intro

== What's in the box?

The Neo4j Java Driver Spring Boot starter provides both a Spring Boot `autoconfigure` and a `starter` module.
The `autoconfigure` module adds a single instance of `org.neo4j.driver.Driver` as a bean to the Spring Context if there is none
and registers health- and metric endpoints for all Driver-beans if the necessary Spring infrastructure is in place.

It does not bring any mapping facilities in addition the available functions of the driver nor Spring Data integration.
Have a look at https://github.com/neo4j/sdn-rx[Spring Data Neo4j⚡️RX] for reactive Spring Data Neo4j repositories.

IMPORTANT: The driver instance is a long living object that provides short living sessions as needed.
The instance does not need to be closed manually, that is done automatically when the application shuts down.
There is no need for external connection pooling.
This is done already in the driver and can be configured via properties.
Please have a look at the chapter {driver_manual_base}/sessions-transactions/[Sessions and transactions].

== Do I need the Neo4j Java Driver Spring Boot starter?

We recommend this starter for all new Spring Boot applications that want to use our new generation of drivers ("4.0").
The next generation of drivers is compatible with both 4.0.x and 3.5.x community and enterprise databases.
The starter takes away all the boilerplate code of configuring an instance of the driver and does support
https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html[externalized configuration]
for all aspects of the driver.

* [*] _You want to work directly with a 4.0 driver?_
The starter is for you.
* [*] _You want Spring Data Neo4j⚡️RX repositories?_
The automatic configuration for SDN-RX is dependent on this starter, so it is already there and you would use exactly
the same as described in this manual to configure your connection
* [*] _You have the previous generation of Spring Data Neo4j or Neo4j-OGM?_
Use the 4.0.x line of this starter with Spring Boot 2.2.x, Spring Data Neo4j 5.2.x and Neo4j-OGM 3.2.x.
Use the 1.7.5.x line of this starter with Spring Boot 2.1.x, Spring Data Neo4j 5.1.x and Neo4j-OGM 3.1.x.
Spring Boot recognizes the driver bean created by this starter and configures Neo4j-OGM accordingly. We also have an <<neo4j-ogm-integration,example for that.>>.
For reference see the https://github.com/neo4j/neo4j-ogm/wiki/Versions[Neo4j-OGM compatibility matrix].

== Does it work with the 1.7 series of the driver?

The 1.7.x line of the starter is for the 1.7.x line of the driver, the 4.0.x line for the 4.0..x of the driver.

== Does it work with the embedded database?

No.

== What's with the long name?

`neo4j-java-driver-spring-boot-starter` is quite a long name for a module, we get that.
However, it follows the official Spring Boot convention described https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-auto-configuration.html#boot-features-custom-starter-naming[here].

> As a rule of thumb, you should name a combined module after the starter. For example, assume that you are creating a starter for "acme" and that you name the auto-configure module acme-spring-boot-autoconfigure and the starter acme-spring-boot-starter. If you only have one module that combines the two, name it acme-spring-boot-starter.

Our "acme" module is the Neo4j Java Driver, project name `neo4j-java-driver` and things add up from there, that's all.
