= Examples
:sectanchors:
ifndef::manualIncludeDir[]
:manualIncludeDir: ../
endif::[]

We provide several examples how to use this starter.

Each example comes with a dedicated readme, that guides you through it.

The examples use the "Movie" data set, that you can install into your instance by going to the http://localhost:7474/browser/?cmd=play&arg=movies[Neo4j Browser].
Enter the command `:play movies` and follow the instructions.

The examples expect an instance with the username `neo4j` and the password `secret`.

All examples use Maven, however they work completely the same with Gradle.

Also, all examples follow Spring Boot conventions, especially:
Use the dependency management and starters, don't provide dependencies for things that are available as a starter.
Use version properties for overwriting any managed version instead of an explicit version.

The examples all have the default main application class, that looks like this:

[source,java]
.A standard Spring Boot main application class
----
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class SimpleApplication {

	public static void main(String[] args) {
		SpringApplication.run(SimpleApplication.class, args);
	}
}
----

NOTE: If you are a https://code.visualstudio.com[Visual Studio Code] user, you'll be happy to see that most of the examples include support for https://code.visualstudio.com/docs/remote/remote-overview[VS Code Remote Development].
      Please follow the instructions at the link above for setting up your Visual Studio Code environment.
      Once setup, you can open the example of your choice inside a VS Code container.
      The running example can be accessed from the outside as shown above without any further actions.

include::{manualIncludeDir}examples/web/README.adoc[]

include::{manualIncludeDir}examples/testing-with-neo4j-harness/README.adoc[]

include::{manualIncludeDir}examples/dedicated-routing-driver/README.adoc[]