= Examples
:sectanchors:
ifndef::manualIncludeDir[]
:manualIncludeDir: ../
endif::[]

We provide several examples how to use this starter.
The reactive demo can only be used with Neo4j version 4.

Each example comes with a dedicated readme, that guides you through it.

The examples use the "Movie" data set, that you can install into your instance by going to the http://localhost:7474/browser/?cmd=play&arg=movies[Neo4j Browser].
Enter the command `:play movies` and follow the instructions.

The examples expect an instance with the username `neo4j` and the password `secret`.

All examples use Maven, however they work completely the same with Gradle.

Also, all examples follow Spring Boot conventions, especially:
Use the dependency management and starters, don't provide dependencies for things that are available as a starter.
Use version properties for overwriting any managed version instead of an explicit version.

The examples all have the default main application class, that looks like this:

[source,java]
.A standard Spring Boot main application class
----
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class SimpleApplication {

	public static void main(String[] args) {
		SpringApplication.run(SimpleApplication.class, args);
	}
}
----

NOTE: If you are a https://code.visualstudio.com[Visual Studio Code] user, you'll be happy to see that most of the examples include support for https://code.visualstudio.com/docs/remote/remote-overview[VS Code Remote Development].
      Please follow the instructions at the link above for setting up your Visual Studio Code environment.
      Once setup, you can open the example of your choice inside a VS Code container.
      The running example can be accessed from the outside as shown above without any further actions.

include::{manualIncludeDir}examples/web/README.adoc[]

include::{manualIncludeDir}examples/reactive-web/README.adoc[]

include::{manualIncludeDir}examples/testing-with-neo4j-harness/README.adoc[]

== Collecting metrics

NOTE: This refers only to Driver metrics, not to the Neo4j server metrics.

`neo4j-java-driver-spring-boot-starter` comes with support for https://micrometer.io[Micrometer metrics] out of the box.
It detects Micrometer on the classpath and binds the metrics of all instances of ` org.neo4j.driver.Driver`, that have enabled their metrics, to a micrometer registry.

Add `org.springframework.boot:spring-boot-starter-actuator` to your Spring Boot application, to include Micrometer.
To enable metrics for the driver instance provided by this starter, set `org.neo4j.driver.config.metrics-enabled` to true then.

You'll find this in the <<Reactive web example>>.
Spring Boot doesn't expose the metrics endpoint over http by default, if you need this, your complete configuration looks like this:

[source,properties]
.application.properties
----
# Enable metrics for the driver instance provided by this starter
org.neo4j.driver.config.metrics-enabled=true

# Expose metrics in addition to info and health over http
management.endpoints.web.exposure.include=info,health,metrics
----

The metrics can be accessed like any other metrics by their name.
The following shows a CURL request retrieving the amount of acquired connections:

[source]
----
curl localhost:8080/actuator/metrics/neo4j.driver.connections.acquired|jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   287  100   287    0     0  32773      0 --:--:-- --:--:-- --:--:-- 35875
{
  "name": "neo4j.driver.connections.acquired",
  "description": "The amount of connections that have been acquired.",
  "baseUnit": "connections",
  "measurements": [
    {
      "statistic": "COUNT",
      "value": 102
    }
  ],
  "availableTags": [
    {
      "tag": "poolId",
      "values": [
        "localhost:7687"
      ]
    },
    {
      "tag": "name",
      "values": [
        "driver"
      ]
    }
  ]
}
----
